#!/bin/bash

# commands retrieved from `code --list-extensions | xargs -L 1 echo "code --install-extension"`

code --install-extension Tyriar.terminal-tabs
code --install-extension Zignd.html-css-class-completion
code --install-extension akamud.vscode-theme-onelight
code --install-extension alefragnani.project-manager
code --install-extension anseki.vscode-color
code --install-extension Arjun.swagger-viewer
code --install-extension be5invis.vscode-icontheme-nomo-dark
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bungcip.better-toml
code --install-extension castwide.solargraph
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cssho.vscode-svgviewer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dunstontc.dark-plus-syntax
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension emilast.LogFileHighlighter
code --install-extension Equinusocio.vsc-material-theme
code --install-extension ericadamski.carbon-now-sh
code --install-extension esbenp.prettier-vscode
code --install-extension felipe-mendes.slack-theme
code --install-extension flowtype.flow-for-vscode
code --install-extension gerane.Theme-Blackboard
code --install-extension GitHub.vscode-pull-request-github
code --install-extension GrapeCity.gc-excelviewer
code --install-extension humao.rest-client
code --install-extension jebbs.plantuml
code --install-extension jock.svg
code --install-extension LaurentTreguier.vscode-simple-icons
code --install-extension lkytal.FlatUI
code --install-extension lunaryorn.fish-ide
code --install-extension mdickin.markdown-shortcuts
code --install-extension mechatroner.rainbow-csv
code --install-extension mermade.openapi-lint
code --install-extension mikestead.dotenv
code --install-extension ms-vscode.Go
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension naumovs.color-highlight
code --install-extension octref.vetur
code --install-extension perragnaredin.light-plus-tweaked
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension rebornix.ruby
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension robertohuertasm.vscode-icons
code --install-extension ryu1kn.partial-diff
code --install-extension Shan.code-settings-sync
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension skyapps.fish-vscode
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tinkertrain.theme-panda
code --install-extension tomoki1207.pdf
code --install-extension vincaslt.highlight-matching-tag
code --install-extension WallabyJs.quokka-vscode
code --install-extension wmaurer.change-case
code --install-extension yzane.markdown-pdf
code --install-extension zhuangtongfa.Material-theme
